config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/questions', to: 'questions#index'

  root 'pages#index'    # корень - это контроллер pages с методом index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    #validates              - установить проверку
    #:title,                - для поля title
    #presence: true         - поле не пустое
    #length: {minimum: 2}   - имеет минимум 2 символа 
    validates :title, presence: true, length: {minimum: 2} 
    validates :body, presence: true, length: {minimum: 2} 

    def formated_created_at 
        created_at.strftime('%Y-%m-%d %H:%M:%S')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base # ? где-то в недрах рельсов есть ActionController::Base ?
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    #layout 'ololo'         # явное указание шаблона
    #layout 'ololo', only: :index         # явное указание шаблона для одного конкретного метода
    #layout 'ololo', only: [:index, :index2]         # явное указание шаблона для конкретных методов (экшенов)

    def index
        #render layout: 'ololo'         # явное указание шаблона
        @params = params
    end  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions = Question.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSandbox(application.html.ebr)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path%></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/ololo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pagesPS(ololo.html.erb)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pagesPS(pages.html.erb)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Qestions', questions_path%></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1><%= @params[:name] %> test pages(index.html.erb)</h1>

&copy; LSVwebDeveloper <%= Time.now.year %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<%= @questions.inspect %>
<h1>each</h1>
<table  width="300" bgcolor="plum" border="1">
    <tbody>
        <% @questions.each do |question| %>
            <tr>
                <td><%= question.id %></td>
                <td><%= question.title %></td>
                <td><%= question.body %></td>
                <td><time datetime="<%= question.formated_created_at %>"><%= question.formated_created_at %></time></td>
            </tr>
        <% end %>
    </tbody>
</table>